export const REQUIRED_ENV_KEYS = [
  "PLAID_CLIENT_ID",
  "PLAID_SECRET",
  "PLAID_ENV",
  "PLAID_PRODUCTS",
  "PLAID_COUNTRY_CODES",
  "PLAID_TRANSACTIONS_DAYS_REQUESTED",
  "PLAID_TOKEN_ENCRYPTION_KEY",
  "CLERK_SECRET_KEY",
  "VITE_CLERK_PUBLISHABLE_KEY",
  "CONVEX_URL",
  "CONVEX_INTERNAL_SECRET",
] as const;

export type RequiredEnvKey = (typeof REQUIRED_ENV_KEYS)[number];
